# Generated by Django 4.2.3 on 2023-08-23 21:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_project_thumbnail2'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprachSkills',
            fields=[
                ('title', models.CharField(max_length=200, null=True)),
                ('body', models.CharField(max_length=36, null=True)),
                ('bg_color', models.CharField(blank=True, max_length=20, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
